version: "3"
services:
  mongo:
    container_name: mongodb-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db-node
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/clean-node-api-test
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api-test/dist
      - ./package.json:/usr/src/clean-node-api-test/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo



